@echo off
cd /d "c:\Users\jalan\OneDrive\Desktop\SevaStream"
echo Initializing git repository...
git init
echo Adding all files...
git add .
echo Committing files...
git commit -m "Initial commit: SevaStream USDC donation platform with complete functionality"
echo Adding remote origin...
git remote add origin https://github.com/hackmayu/SevaStream-Stream-Hope-Create-Impact.git
echo Setting main branch...
git branch -M main
echo Pushing to GitHub...
git push -u origin main
echo Done! Your code has been pushed to GitHub.
pause
