@echo off
cd /d "c:\Users\jalan\OneDrive\Desktop\SevaStream"
echo Initializing git repository...
git init
echo Adding all files...
git add .
echo Committing files...
git commit -m "Initial commit: SevaStream USDC donation platform with complete functionality"
echo Adding remote origin...
git remote add origin https://github.com/hackmayu/SevaStream-Stream-Hope-Create-Impact.git
echo Setting main branch...
git branch -M main
echo Pushing to GitHub...
git push -u origin main

echo.
echo ====================================
echo Pushing Updated README.md Changes
echo ====================================
echo Adding new README.md changes...
git add README.md
echo Committing README updates...
git commit -m "Enhanced README.md with screenshots section and feature highlights"
echo Pushing README updates to GitHub...
git push origin main
echo.
echo Done! Your updated README.md has been pushed to GitHub.
pause
